### PR TITLE
Enable eslint and fix linter's errors

### LINKED ISSUE #16: Eslint should be enabled for all components
Eslint should be enabled for all components and errors resolved
Remaining components:
- components/club-full/club-full.js
- components/leader-tools/leader-tools.js
- components/member/member.js
- components/opportunities-guest/opportunities-guest.js
- pages/organizations.js

### PR DESCRIPTION
**Pull request by dPliakos**
Remove `eslint-disable` note from all components. 
Add `gaatsby-eslintplugin` in order for the eslint to run when gatsby updates the dev server. 
Add accessibility features.

Fix #16

### CODE REVIEW

File: gatsby-config.js [hunk 1]
```diff
@@ -55,10 +55,21 @@ module.exports = {
...
-        display: 'minimal-ui',
+        display: 'minimal-ui'
         // icon: 'src/images/gatsby-icon.png', // This path is relative to the root of the site.
-      },
+      }
     },
     'gatsby-plugin-offline',
-  ],
+    {
+      resolve: 'gatsby-plugin-eslint',
```
Comment (dPliakos) [inline gatsby-config.js]: @alexdor  I added `gatsby-plugin-eslint` in order the eslint to run  at the dev environment.
Is this something we wanted to avoid?

Comment (iropal) [reply gatsby-config.js]: @alexdor @dPliakos I merged this pr because it had changes in multiple files and would be very difficult to resolve conflicts later (the changes are not all auto generated by the linter). We can change the configuration in another pr if we need to.
